V.cmd("nnoremap <silent> gp <cmd>Lspsaga peek_definition<CR>")
V.cmd("nnoremap <silent> gd <cmd>Lspsaga goto_definition<CR>")
V.cmd("nnoremap <silent> gD <cmd>lua vim.lsp.buf.declaration()<CR>")
V.cmd("nnoremap <silent> gr <cmd>Lspsaga finder ref<CR>")
V.cmd("nnoremap <silent> gi <cmd>Lspsaga finder imp<CR>")
V.cmd("nnoremap <silent> K <cmd>Lspsaga hover_doc<CR>")
V.cmd("nnoremap <silent> <leader>la <cmd>lua vim.lsp.buf.code_action()<CR>")
V.cmd("nnoremap <silent> <leader>lr <cmd>Lspsaga rename<CR>")
V.cmd("nnoremap <silent> <A-n> <cmd>Lspsaga diagnostic_jump_next<CR>")
V.cmd("nnoremap <silent> <A-p> <cmd>Lspsaga diagnostic_jump_prev<CR>")
V.cmd("nnoremap <silent> <C-space> <cmd>lua vim.lsp.buf.completion()<CR>")
V.cmd("nnoremap <silent> <leader>ll <cmd>Lspsaga show_line_diagnostics<CR>")
V.cmd('command! -nargs=0 LspVirtualTextToggle lua require("lsp/virtual_text").toggle()')
