#theme = "solarized-dark"
#icons = "awesome"

[theme]
name = "solarized-dark"

[icons]
name = "awesome"

[theme.overrides]
separator = ""

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "focused_window"
max_width = 25

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "net"
device = "wlo1"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "battery"
interval = 10
device = "BAT0"
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %l:%M"
