[colors.bright]
black = "0x454C59"
blue = "0x69BBFF"
cyan = "0x66D9E8"
green = "0xB5E890"
magenta = "0xE48AFF"
red = "0xFF7A85"
white = "0xCFD7E6"
yellow = "0xFFD68A"

[colors.normal]
black = "0x282C34"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xABB2BF"
yellow = "0xE5C07B"

[colors.primary]
background = "0x282C34"
foreground = "0xABB2BF"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono NFM"

[font.italic]
family = "JetBrainsMono NFM"

[font.normal]
family = "JetBrainsMono NFM"

[shell]
# args = ["-l", "-c", '''tmux attach || exec tmux new-session -s scratch -n notas 'nvim -c "chdir ~/notas" -c "edit index.md"' \; neww''']
args = ["-l", "-c", '''tmux attach || exec tmux new-session -n notas 'nvim -c "chdir ~/notas" -c "edit index.md"' \; neww''']
program = "zsh"

[window]
decorations = "Full"

[window.dimensions]
columns = 70
lines = 25
