#!/bin/sh
echo "Fetching device IP"
IP=$(ifconfig 2>/dev/null | grep -Po '(?<=inet )(?!127)(\d{1,3}\.?){4}')
echo "Device IP: ${IP}"
printf "Type sync port: "
read SYNC_PORT

adb pair "${IP}:${SYNC_PORT}"

printf "Type connection port: "
read CONNECTION_PORT

adb connect "${IP}:${CONNECTION_PORT}"
adb tcpip 5555

ADB_RESULT=$?

echo ""

if [ $ADB_RESULT -eq 0 ]
then
	echo "adb wifi enabled"
else
	echo "Something went wrong"
fi
