#!/bin/sh
FECHA="$(date +%Y-%m-%d)"
NOMBRE_ARCHIVO="$HOME/notas/cap-$FECHA.md"

# Si el archivo no existe, lo creamos
if [ ! -f $NOMBRE_ARCHIVO ]; then
	TITULO="$(date +'%A %d de %B de %Y')"
	echo "# Notas de $TITULO" > $NOMBRE_ARCHIVO
	echo "- [$FECHA](cap-$FECHA)" >> "$HOME/notas/hub_capturas.md"
	echo "- [ ] [$FECHA](cap-$FECHA)" >> "$HOME/notas/index.md"
else
	LINK=(grep -E "(- \[[ |X]\] \[$FECHA\]\(.*))" $HOME/notas/index.md)

	if [ $("${LINK[@]}" | wc -l) -gt 0 ]; then
		# Si el link existe, se actualiza
		sed -i "s+- \[X\] \[$FECHA\]\(.*\)+- [ ] [$FECHA](cap-$FECHA)+g" $HOME/notas/index.md
	else
		# De lo contrario, se agrega
		echo "- [ ] [$FECHA](cap-$FECHA)" >> "$HOME/notas/index.md"
	fi
fi

nvim -c "norm Go" \
	-c "norm Go## $(date +%H:%M)" \
	-c "norm G2o" \
	-c "norm zz" \
	-c "startinsert" $NOMBRE_ARCHIVO \
	-c "chdir $HOME/notas"
