#!/bin/sh
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias diff='diff --color=auto'

# confirm before overwriting something
alias history="history 100"
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

if ! command -v exa &> /dev/null
then
	alias ls='ls --color=auto'
else
	alias ls='exa --icons'
fi

alias du='du -had 1'
alias siepyt='cd ~/Documentos/Escuela/Semestre\ 10/Ingeniería\ web/siepyt'
alias viminit='nvim --cmd "chdir ~/.config/nvim" ~/.config/nvim/init.lua'
alias notas='nvim -c "chdir ~/notas" ~/notas/index.md'
alias scrcpyd='devour scrcpy'
alias escuela='cd /home/aristeo/Documentos/Escuela'
alias proyectos='cd /home/aristeo/Documentos/Proyectos\ secundarios'
alias cursos='cd /home/aristeo/Documentos/Cursos'
alias documentos='cd /home/aristeo/Documentos'
alias dotfiles='cd /home/aristeo/Documentos/dotfiles'
alias descargas='cd /home/aristeo/Downloads'
alias capture='/home/aristeo/scripts/capture'
alias clip='xclip -sel clip'
alias svim='sudo -E -s nvim'
