vim.cmd('source ~/.config/nvim/vimscript/generalvscode.vim')
vim.cmd('source ~/.config/nvim/vimscript/general.vim')
require('globals')
require('plugins')
require('nv_treesitter')
require('nv_telescope')
-- Este es el bueno de las capturas, pero si lo uso se aloca
-- require('capture')
require('nv_telescope.buscadores')
require('nv_bufferline')
require('nv_lualine')
require('nv_compe')
vim.cmd('source ~/.config/nvim/vimscript/nvim-tree.vim')
vim.cmd('source ~/.config/nvim/vimscript/indentLine.vim')
vim.cmd('source ~/.config/nvim/vimscript/whichkey.vim')
vim.cmd('source ~/.config/nvim/vimscript/gitgutter.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimspector.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimwiki.vim')
vim.cmd('source ~/.config/nvim/vimscript/keymaps.vim')
vim.cmd('source ~/.config/nvim/vimscript/autocommands.vim')
require('nv_base16')

-- LSP
require('lsp')
require('lsp.python')
require('lsp.bash')
require('lsp.java')
