#!/bin/sh
FECHA="$(date +%Y-%m-%d)"
NOMBRE_ARCHIVO="$HOME/notas/capturas/$FECHA.md"

if [ ! -f $NOMBRE_ARCHIVO ]; then
	TITULO="$(date +'%A %d de %B de %Y')"
	echo "# Notas de $TITULO" > $NOMBRE_ARCHIVO
	echo "- [[$FECHA]]" >> "$HOME/notas/capturas/capturas.md"
fi

nvim -c "norm Go" \
	-c "norm Go## $(date +%H:%M)" \
	-c "norm G2o" \
	-c "norm zz" \
	-c "startinsert" $NOMBRE_ARCHIVO \
	-c "chdir $HOME/notas"
