#!/bin/python
from time import strftime
import re

today = strftime('%Y-%m-%d')
tags = [
    ('', 'Laptop'),
    ('', 'Tramites'),
    ('', 'Tramites'),
]


def get_due_dates(text):
    """Finds all due dates in file"""
    dates = re.findall("(due):([0-9]{4}-[0-1][0-9]-[0-3][0-9])", text)
    return [date[1] for date in dates]


def count_todays_tasks(dates, today):
    """Compares today's date with every date found in the file."""
    return dates.count(today)


def count_passed_tasks(dates, today):
    """Counts every due date before todays date"""
    passed = 0
    for date in dates:
        if date < today:
            passed += 1
    return passed


def main(tags):
    file = open('/home/aristeo/notas/todo.txt')
    # Reading the file contents as a string
    tasks = file.read()

    # Checking the total ammount of tasks
    total = tasks.count('\n')
    if total == 0:
        return ''

    result = ''

    due_dates = get_due_dates(tasks)
    passed = count_passed_tasks(due_dates, today)
    due = count_todays_tasks(due_dates, today)
    if passed > 0:
        result = f'!{passed} / '
    if due > 0:
        result = f' {due} / '

    # Checking for every tag
    for tag in tags:
        pending = tasks.count(tag[1])
        if pending > 0:
            result += f'{tag[0]} {pending} / '

    return(f'{result} {total}')


print(main(tags))
