#!/bin/python
from time import strftime
import re

today = strftime('%Y-%m-%d')
tags = [
    ('', 'Laptop'),
    ('', 'Tramites'),
    ('', 'Tramites'),
    ('', today)
]


def count_passed_tasks(text, today):
    """Compares today's date with every date found in the file."""
    passed = 0
    # Only captures dates with the due tag
    dates = re.findall("(due):([0-9]{4}-[0-1][0-9]-[0-3][0-9])", text)
    for date in dates:
        if date[1] < today:
            passed += 1
    return passed


def main(tags):
    file = open('/home/aristeo/notas/todo.txt')
    # Reading the file contents as a string
    tasks = file.read()

    # Checking the total ammount of tasks
    total = tasks.count('\n')
    if total == 0:
        return ''

    result = ''
    passed = count_passed_tasks(tasks, today)
    if passed > 0:
        result = f'!{passed} / '

    # Checking for every tag
    for tag in tags:
        pending = tasks.count(tag[1])
        if pending > 0:
            result += f'{tag[0]} {pending} / '

    return(f'{result} {total}')


print(main(tags))
